[package]
name = "try-rs-release-please"
version = "0.3.0"
edition = "2021"
license = "Apache-2.0"
rust-version = "1.74"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
